module.exports = ["consume 0",
		  "crossfade 1",
		  "mixrampdb 0",
		  "mixrampdelay 0",
		  "random 0",
		  "repeat 0",
//		  "setvol 0",
		  "single 0",
		  "replay_gain_mode off",
		  "replay_gain_status",
		  "next",
		  "pause 0",
		  "play 0",
		  "playid 0",
		  "previous",
 "seek 0 0",
 "seekid 0 0",
 "seekcur 0",
 "stop",
// "add",
// "addid",
// "delete",
// "deleteid",
// "move",
// "moveid",
 "playlist",
// "playlistfind",
/* "playlistid",
 "playlistinfo",
 "playlistsearch",
 "plchanges",
 "plchangesposid",
 "prio",
 "prioid",*/
 "shuffle 0",
// "swap",
// "swapid",
// "addtagid",
// "cleartagid",
 "listplaylist",
 "listplaylistinfo",
 "listplaylists",
 "load",
 "playlistadd",
 "playlistclear",
 "playlistdelete",
 "playlistmove",
 "rename",
 "rm",
 "save",
 "count",
 "find",
 "findadd",
 "list",
 "listall",
 "listallinfo",
 "listfiles",
 "lsinfo",
 "readcomments",
 "search",
 "searchadd",
 "searchaddpl",
 "update",
 "rescan",
// "sticker",
// "close",
// "kill",
// "password",
		  "ping",
		  "clearerror",
		  "currentsong",
//		  "idle",
		  "status",
		  "stats",
		  "clear"];
